urls.py
from django.conf.urls import url, patterns, include
import DOCS.views
from . import views
from DOCS.views import RequirementList

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^requirements/$', RequirementList.as_view()),
    url(r'^(?P<requirement_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^merchant/(?P<merchant_name>[-\w]+)/$', views.merchant, name='merchant'),
    url(r'^merchant/(?P<merchant_name_URL>[-\w]+)/(?P<version>[\w.]+)/(?P<saq_req>[\w]+)/(?P<req_number>[\w.]+)/$', views.merchant_requirement, name='merchant_requirement'),
    
    
]

models.py
from django.db import models
from datetime import datetime, timedelta
from django.template.defaultfilters import slugify
from django.forms import ModelForm
import markdown


class SAQ(models.Model):
    saq_name = models.CharField(max_length=200)
    saq_version = models.CharField(max_length=200)
    saq_risk = models.IntegerField(blank=True, null=True, default=0)
    saq_description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.saq_version + " " + self.saq_name


class Merchant(models.Model):
    merchant_name = models.CharField(max_length=200)
    merchant_name_URL = models.CharField(max_length=200, null=True, blank=True, default='')
    merch_percent = models.FloatField(null=True, blank=True, default=0)
    req_complete = models.IntegerField(blank=True, null=True, default=0)
    total_req = models.IntegerField(blank=True, null=True, default=0)
    merchant_URL = models.URLField(max_length=2000, blank=True, null=True)
    merchant_contact_name = models.CharField(max_length=100, blank=True, null=True)
    merchant_contact_uvid = models.CharField(max_length=8, blank=True, null=True)
    merchant_contact_phone = models.CharField(max_length=15, blank=True, null=True)
    merchant_contact_email = models.EmailField(blank=True, null=True)
    merchant_business_description = models.TextField(blank=True, null=True, help_text="Description of the merchant’s payment card business. This is not intended to be a cut-and-paste from the department’s website, but should be a tailored description that shows the assessor understands the business of the merchant being assessed.")
    merchant_card_processing_description = models.TextField(blank=True, null=True, help_text="Describe how and why the merchant stores, processes, and/or transmits cardholder data. This is not intended to be a cut-and-paste from above, but should build on the understanding of the business and the impact this can have upon the security of cardholder data.")
#    merchant_payment_channels = models.TextField(blank=True, null=True, help_text="What types of payment channels the merchant serves, such as card-present and card-not-present (for example, mail order/telephone order (MOTO), e-commerce).")
    merchant_third_parties = models.TextField(blank=True, null=True, help_text="Any entities that the assessed merchant connects to for payment transmission or processing, including processor relationships.")
    # file will be saved to MEDIA_ROOT/uploads/2015/01/30
    merchant_network_diagram = models.FileField(upload_to='network-diagram', blank=True, null=True, help_text="Provide a high-level network diagram (either obtained from the entity or created by assessor) of the entity’s networking topography, showing the overall architecture of the environment being assessed. This high-level diagram should summarize all locations and key systems, and the boundaries between them and should include the following: Connections into and out of the network including demarcation points between the cardholder data environment (CDE) and other networks/zones Critical components within the cardholder data environment, including POS devices, systems, databases, and web servers, as applicable Other necessary payment components, as applicable")
    merchant_process_identify_data = models.TextField(blank=True, null=True, help_text="Describe the methods or processes (for example, tools, observations, feedback, scans, data flow analysis) used to identify and document all existences of cardholder data (as executed by the assessor, assessed entity or a combination):")
    merchant_process_no_data_outside_cde = models.TextField(blank=True, null=True, help_text="Describe the methods or processes (for example, tools, observations, feedback, scans, data flow analysis) used to verify that no cardholder data exists outside of the defined CDE (as executed by the assessor, assessed entity or a combination):")
    merchant_scope_review_process = models.TextField(blank=True, null=True, help_text="Describe how the results of the methods/processes were evaluated by the assessor to verify that the PCI DSS scope of review is appropriate:")
    merchant_scope_documentation = models.TextField(blank=True, null=True, help_text="Describe how the results of the methods/processes were documented (for example, the results may be a diagram or an inventory of cardholder data locations):")
    merchant_scope_reasoning = models.TextField(blank=True, null=True, help_text="Describe why the methods (for example, tools, observations, feedback, scans, data flow analysis) used for scope verification are considered by the assessor to be effective and accurate:")
    merchant_cde_people = models.TextField(blank=True, null=True, help_text="People – such as technical support, management, administrators, operations teams, cashiers, telephone operators, etc.: Note – this is not intended to be a list of individuals interviewed, but instead a list of the types of people, teams, etc. who were included in the scope.")
    merchant_cde_processes = models.TextField(blank=True, null=True, help_text="Processes – such as payment channels, business functions, etc.:")
    merchant_cde_technologies = models.TextField(blank=True, null=True, help_text="Technologies – such as e-commerce systems, internal network segments, DMZ segments, processor connections, POS systems, etc.: Note – this is not intended to be a list of devices but instead a list of the types of technologies, purposes, functions, etc. included in the scope.")
    merchant_cde_locations = models.TextField(blank=True, null=True, help_text="Locations/sites/stores – such as retail outlets, data centers, corporate office locations, call centers, etc.:")
    merchant_network_segmentation = models.TextField(blank=True, null=True, help_text="Identify whether the assessed entity has used network segmentation to reduce the scope of the assessment. (yes/no) Explain how the assessor validated the effectiveness of the segmentation, as follows: Describe the methods used to validate the effectiveness of the segmentation (for example, observed configurations of implemented technologies, tools used, network traffic analysis, etc.). Describe how it was verified that the segmentation is functioning as intended. Describe how it was verified that adequate security controls are in place to ensure the integrity of the segmentation mechanisms (e.g., access controls, change management, logging, monitoring, etc.).")
    merchant_cde_networks = models.TextField(blank=True, null=True, help_text="Describe all networks that store, process and/or transmit CHD:")
    merchant_in_scope_networks = models.TextField(blank=True, null=True, help_text="Describe all networks that do not store, process and/or transmit CHD, but are still in scope (e.g., connected to the CDE or provide management functions to the CDE):")
    merchant_out_of_scope_networks = models.TextField(blank=True, null=True, help_text="Describe any networks confirmed to be out of scope:")
    merchant_processing_entities = models.TextField(blank=True, null=True, help_text="Identify All Processing Entities (Acquirer/ Bank/ Brands directly connected to for processing)")
    merchant_wireless = models.TextField(blank=True, null=True, help_text="If there are no wireless networks or technologies in use, describe how this was verified by the assessor. If there are wireless networks or technologies in use, identify and describe all wireless technologies in use that are connected to or could impact the security of the cardholder data environment. This would include : Wireless LANs, Wireless payment applications (for example, POS terminals), All other wireless devices/technologies")
    merchant_data_flow_authorization = models.TextField(blank=True, null=True, help_text="Describe how cardholder data is transmitted and/or processed and for what purpose it is used")
    merchant_data_flow_capture = models.TextField(blank=True, null=True, help_text="Describe how cardholder data is transmitted and/or processed and for what purpose it is used")
    merchant_data_flow_settlement = models.TextField(blank=True, null=True, help_text="Describe how cardholder data is transmitted and/or processed and for what purpose it is used")
    merchant_data_flow_chargeback = models.TextField(blank=True, null=True, help_text="Describe how cardholder data is transmitted and/or processed and for what purpose it is used")
    merchant_card_storage = models.TextField(blank=True, null=True, help_text="Identify and list all databases, tables, and files storing cardholder data and provide the following details. Note: The list of files and tables that store cardholder data in the table below must be supported by an inventory created (or obtained from the client) and retained by the assessor in the work papers.")
    merchant_sampling = models.TextField(blank=True, null=True, help_text="Identify whether sampling was used during the assessment. Describe the sampling rationale and/or standardized PCI DSS security and operational processes/controls used for selecting sample sizes (for people, processes, technologies, devices, locations/sites, etc.).")

#    saq_a = 'A'
#    saq_aep = 'A-EP'
#    saq_b = 'B'
#    saq_c = 'C'
#    saq_cvt = 'C-VT'
#    saq_d = 'D'
#    saq_p2pe = 'P2PE'
#
#    saq_choices = (
#        (saq_a, 'SAQ A'),
#        (saq_aep, 'SAQ A-EP'),
#        (saq_b, 'SAQ B'),
#        (saq_c, 'SAQ C'),
#        (saq_cvt, 'SAQ C-VT'),
#        (saq_d, 'SAQ D'),
#        (saq_p2pe, 'SAQ P2PE'),
#    )
#    saq_req =models.CharField(max_length=4,
#                            choices=saq_choices,
#                            default=saq_d)
    saq_req = models.ForeignKey(SAQ, blank=True, null=True)

    def __str__(self):
        return self.merchant_name

    def save(self, *args, **kwargs):
        self.merchant_name_URL = slugify(self.merchant_name)

templates/DOCS/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'DOCS/favicon.ico' %}">

    <title>{% block title %}PCI Documentation of Compliance and Security{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'DOCS/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'DOCS/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="{% static 'DOCS/css/dashboard.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

   <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">PCI DOCS</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Merchants</a></li>
            <li><a href="/admin/">Admin</a></li>
            <li><a href="/logout/">Logout</a></li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% block sidebar %}{% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">{% block header %}PCI Documentation of Compliance and Security{% endblock %}</h1>
                {% block content %} {% endblock %}
        </div>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'DOCS/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'DOCS/js/bootstrap.js' %}"></script>

  </body>
</html>

templates/DOCS/detail.html
<h1>{{ requirement }}</h1>
<h1>{{ saqrequirement }}</h1>
<ul>
<ul>

    {{ requirement }}
    {% for testing_procedure in requirement.testing_procedure_set.all %}
        <li>
            {{ testing_procedure }}
            {% for testing_sub_procedure in testing_procedure.testing_sub_procedure_set.all %}
            <ul>
                <li>
                {{ testing_sub_procedure }}
                </li>
            </ul>
            {% endfor %}
        </li>
            <p>
            {% for reporting_instruction in testing_procedure.reporting_instruction_set.all %}
            <ul>
                <li>
                {{ reporting_instruction }}
                    {% for reporting_sub_instruction in reporting_instruction.reporting_sub_instruction_set.all %}
                 <ul>
                    <li>
                    {{ reporting_sub_instruction }}
                    </li>
                </ul>
                    {% endfor %}
                </li>
            </ul>
            {% endfor %}
            </p>
        </li>
    
    
        {% for guidance in requirement.guidance_set.all %}
            <p>
                {{ guidance }}
            </p>
        {% endfor %}
    </ul>
    {% endfor %}

templates/DOCS/index.html
{% extends "DOCS/base.html" %}
{% load DOCS_extras %}


{% block title %}PCI DOCS{% endblock %}
        {% block sidebar %}

            <h4>Campus Merchants</h4>


            <ul class="nav nav-sidebar">

            {% nav_merchantlist %}
          </ul>

        {% endblock %}
{% block header %}Campus Merchants{% endblock %}

{% block content %}
{% if merchant_list %}
    {% for saq in saq_list %}
        {% if saq.merchant_set.all.count > 0 %}
            <div class="list-group">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>SAQ {{ saq }}</strong></h3>

                        {% if saq.saq_description %}
                            </br>
                            {{ saq.saq_description|safe }}
                        {%  endif %}
                    </div>
                {% for merchant in merchant_list %}
                    {% if merchant.saq_req == saq %}
                        {% if merchant.merch_percent <= 0 %}
                           <a href="/merchant/{{ merchant.merchant_name_URL }}/" class="list-group-item list-group-item-danger"><strong>{{ merchant }}</strong>

                               <span class="badge">{{ merchant.req_complete }} / {{ merchant.total_req }}</span></a>
                        {% elif merchant.merch_percent < 100 %}
                           <a href="/merchant/{{ merchant.merchant_name_URL  }}/"  class="list-group-item list-group-item-warning"><strong>{{ merchant }}</strong>

                               <span class="badge">{{ merchant.req_complete }} / {{ merchant.total_req }}</span></a>
                        {% else %}
                           <a href="/merchant/{{ merchant.merchant_name_URL  }}/"  class="list-group-item list-group-item-success"><strong>{{ merchant }}</strong>

                               <span class="badge">{{ merchant.req_complete }} / {{ merchant.total_req }}</span></a>

                        {% endif %}
                    {% endif %}
                {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endfor %}


{% endif %}
{% endblock %}

templates/DOCS/merch_requirement.html
{% extends "DOCS/base.html" %}
{% load DOCS_extras %}


{% block title %}PCI DOCS{% endblock %}
        {% block sidebar %}
            <ul class="nav nav-sidebar">
             <li><a href="/">Campus Merchants:</a></li>
            {% nav_merchantlist %}
          </ul>

        {% endblock %}
{% block header %}{{ merchant }}{% endblock %}

{% block content %}
{% if requirement.parent_req = None %}
<ol class="breadcrumb">
  <li><a href="/merchant/{{ merchant.merchant_name_URL  }}/">{{ merchant }}</a></li>
</ol>
{% elif requirement.parent_req.parent_req.req_number%}
<ol class="breadcrumb">
  <li><a href="/merchant/{{ merchant.merchant_name_URL  }}/">{{ merchant }}</a></li>
  <li><a href="../{{ requirement.parent_req.parent_req.req_number }}/">{{ requirement.parent_req.parent_req.req_number }}</a></li> 
  <li><a href="../{{ requirement.parent_req.req_number }}/">{{ requirement.parent_req.req_number }}</a></li>
</ol>
{% else %}
<ol class="breadcrumb">
  <li><a href="/merchant/{{ merchant.merchant_name_URL  }}/">{{ merchant }}</a></li>
  <li><a href="../{{ requirement.parent_req.req_number }}/">{{ requirement.parent_req.req_number }}</a></li>
</ol>
{% endif %}
<h3>{{ requirement.req_name_number|safe }} </h3>
{% if requirement.req_status = 'Not In Place' %}
    <div class="alert alert-danger" role="alert">
             <strong>{{ requirement.req_status }} </strong>
    </div>
{% elif requirement.req_status  = 'In Place' %}
    <div class="alert alert-success" role="alert">
             <strong>{{ requirement.req_status }} </strong>
    </div>
{% elif requirement.req_status  = 'In Progress' %}
    <div class="alert alert-warning" role="alert">
             <strong>{{ requirement.req_status }} </strong>
    </div>
{% elif requirement.req_status  = 'Not Applicable' %}
    <div class="alert alert-info" role="alert">
             <strong>{{ requirement.req_status }} </strong>
    </div>
{% endif %}

{% if requirement.req_note  %}
     <div class="well">
     
              {{ requirement.req_note|safe }}
     </div>
{% endif %}
{% if requirement.guidance_text  %}
     <div class="well">
     
              {{ requirement.guidance_text|safe }}
     </div>
{% endif %}
{% if requirement.req_test_summ  %}
     <div class="well">

              {{ requirement.req_test_summ|safe }}
     </div>
{% endif %}

{% for child_req in requirement.child_req.all %}
      {% if child_req.merchant = merchant %}
            {% if child_req.req_status = 'Not In Place' %}
               <a href="../{{ child_req.req_number }}/" class="list-group-item list-group-item-danger">{{ child_req.req_name_number|safe }} </a>
            {% elif child_req.req_status = 'In Progress' %}
               <a href="../{{ child_req.req_number }}/" class="list-group-item list-group-item-warning">{{ child_req.req_name_number|safe }} </a>
            {% elif child_req.req_status = 'In Place' %}
               <a href="../{{ child_req.req_number }}/" class="list-group-item list-group-item-success">{{ child_req.req_name_number|safe }} </a>
            {% elif child_req.req_status = 'Not Applicable' %}
               <a href="../{{ child_req.req_number }}/" class="list-group-item list-group-item-info">{{ child_req.req_name_number|safe }} </a>
            {% endif %}
      {% endif %}
      
{% endfor %}
<div class="row"><p></p></div>
{% for testing_procedure in requirement.testing_procedure_set.all %}
     <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
               {{ testing_procedure|safe }}
            
            </div>
            <div class="panel-body">
             
                {{ testing_procedure.rep_inst_text|safe }}
            
            </div>
            

             
        </div>
        
      </div>
{% endfor %}
{% if requirement.testing_procedure_set.all  %}
    
         <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                   Findings:
            </div>
            <div class="panel-body">
             <form action="./" method="post" class="form-horizontal">
                 {% csrf_token %}
                 {{ form.non_field_errors }}
                 {{ form.non_field_errors }}
                 <div class="form-group">
                    {{ form.finding_text.errors }}
                    <label for="{{ form.finding_text.id_for_label }}" class="col-sm-2 control-label">Finding Text:</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="{{ form.finding_text.id_for_label }}" name="finding_text" rows="3"></textarea>
                        </div>
                 </div>
                 <div class="form-group">
                    {{ form.status.errors }}
                    <label for="{{ form.status.id_for_label }}" class="col-sm-2 control-label">Status:</label>
                    <div class="col-sm-10">
                        <select class="form-control" id="{{ form.status.id_for_label }}" name="status">
                        <option value="Not In Place">Not In Place</option>
                        <option value="In Place">In Place</option>
                        <option value="In Progress">In Progress</option>
                        <option value="Not Applicable">Not Applicable</option>
                        </select>
                    </div>
                 </div>
                 <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default" value="Submit" />Submit</button>
                    </div>
                 </div>
             </form>
            {% for finding in requirement.finding_set.all|dictsortreversed:"finding_date"|slice:"3" %}
            <ul class=list-group>
              <li class=list-group-item>
                  {{ finding }} ----  {{ finding.finding_date }} 
              </li>  
             </ul>
            {% endfor %}
            </div>
        </div>
        
      </div> 
    
    
{% endif %}


{% endblock %}

templates/DOCS/merchant_list.html
              {% for merchant in merchants %}
                    <li><a  href="/merchant/{{ merchant.merchant_name_URL }}/">{{ merchant }} </a></li>
              {% endfor %}

templates/DOCS/requirement_list.html
{% extends "DOCS/base.html" %}
{% load DOCS_extras %}


{% block title %}PCI DOCS{% endblock %}
        {% block sidebar %}
            <ul class="nav nav-sidebar">
             <li><a href="/">Merchants: </a></li>
            {% nav_merchantlist %}
          </ul>

        {% endblock %}
{% block header %}PCI Requirements{% endblock %}

{% block content %}
    <ul>
        {% for requirement in object_list %}
            <li>{{ requirement }}</li>
        {% endfor %}
    </ul>

{% endblock %}